install.packages("https://cran.r-project.org/src/contrib/remotes_2.4.2.tar.gz")
install.packages("R.utils")
remotes::install_version("targets", version = "0.1.0")
remotes::install_version("tarchetypes", version = "0.0.4")
remotes::install_version("markdown", version = "1.1")
remotes::install_version("rmarkdown", version = "2.6")
remotes::install_version("visNetwork", version = "2.0.9")
remotes::install_version("kableExtra", version = "1.3.1")
remotes::install_version("tidyverse", version = "1.3.0", upgrade = "never")
remotes::install_version("spatstat", version = "1.64-1")
remotes::install_version("BiocManager", version = "1.30.10")