---
title: "Dataset Stats"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Save metadata file from integrated Seurat object

```{r}
sobj <- tar_read(archived_sobj)
cell_data <- get_cell_data(sobj)
write_csv(cell_data, "data/cell_metadata.csv")
```

## Plot transcript and gene distribution per sample

```{r}
ggplot(cell_data, aes(x = Sample_Name, y = nCount_RNA)) +
  geom_boxplot(aes(fill = Sample_Name)) +
  labs(y = "Unique Transcripts",
       x = "Sample") +
  theme_bw()

ggsave("plots/UMI_stats.pdf", family = "ArialMT")

ggplot(cell_data, aes(x = Sample_Name, y = cell_data$nFeature_RNA)) +
  geom_boxplot(aes(fill = Sample_Name)) +
  labs(y = "Unique Genes",
       x = "Sample") +
  theme_bw()

ggsave("plots/gene_stats.pdf", family = "ArialMT")
```

## Plot cell type for all cells in UMAP space.

```{r}
color_scheme <- cell_data %>%
    dplyr::select(Cluster_Type, Color) %>%
    unique() %>%
    deframe()

ggplot(cell_data %>% arrange(UMAP_1), aes(x = UMAP_1, y = UMAP_2)) + 
    geom_point(aes(color = Cluster_Type), size = 1) +
    scale_color_manual(values = color_scheme, name = "Cell Type") +
    guides(color = guide_legend(override.aes = list(size = 3))) +
    labs(x = "UMAP 1", y = "UMAP 2") +
    coord_fixed() +
    theme_void() +
    theme(axis.title.x = element_text(hjust = 0)) +
    theme(axis.title.y = element_text(hjust = 0, angle = 90))

ggsave("plots/umap_celltype.pdf", family = "ArialMT")
```

## Proportion of cells belong to DC3000-treated sample in UMAP space

```{r}
ggplot(cell_data %>% arrange(UMAP_1), aes(x = UMAP_1, y = UMAP_2, group = -1)) +
    stat_summary_hex(aes(z = Sample_Name == "DC3000"), fun = mean, binwidth = 0.25, color = 'black', lwd = 0.1) +
    scale_fill_viridis_c(option = "plasma", name = "Proportion DC3000-Treated Cells") +
    labs(x = "UMAP 1", y = "UMAP 2") +
    coord_fixed() +
    theme_void() +
    theme(axis.title.x = element_text(hjust = 0)) +
    theme(axis.title.y = element_text(hjust = 0, angle = 90))

ggsave("plots/umap_sampledensity.pdf", family = "ArialMT")
```

## Pathogen response score per cell on UMAP

```{r}
ggplot(cell_data %>% arrange(UMAP_1), aes(x = UMAP_1, y = UMAP_2)) +
  geom_point(aes(color = DC3000.Up1 - DC3000.Down1), size = 0.5) +
    scale_color_viridis_c(option = "plasma", name = "Pathogen signature score") +
    labs(x = "UMAP 1", y = "UMAP 2") +
    coord_fixed() +
    theme_void() +
    theme(axis.title.x = element_text(hjust = 0)) +
    theme(axis.title.y = element_text(hjust = 0, angle = 90))

ggsave("plots/umap_signaturescore.pdf", family = "ArialMT")

```

## Bar plots of sample and cell types for each cluster

```{r}
base_clusterplt <- cell_data %>%
  mutate(Cluster_Type = case_when(
    Cluster %in% paste0("M", 1:5) ~ "Pathogen-responsive Mesophyll",
    Cluster %in% paste0("M",6:14) ~ "Other Mesophyll",
    !(Cluster %in% paste0("M",1:14)) ~ "Other Cell Types"
  )) %>%
  mutate(Cluster_Type = factor(Cluster_Type, levels = c(
    "Pathogen-responsive Mesophyll",
    "Other Mesophyll",
    "Other Cell Types"
  ))) %>%
  mutate(Cluster = factor(Cluster, levels = c(paste0("M",1:14), "B15", "P16", "G17", "C18"))) %>%
  ggplot(aes(x = Cluster))

base_clusterplt +
  geom_bar(aes(fill = Sample_Name)) +
  scale_fill_discrete(name = "Sample") +
  scale_y_continuous(limits = c(0,2000), expand = c(0,0)) +
  facet_grid(1 ~ Cluster_Type, 
             space = 'free', 
             scales = 'free', labeller = label_wrap_gen(width = 10)) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        strip.text.y = element_blank(),
        strip.background.y = element_blank(),
        strip.background.x = element_blank())

ggsave("plots/cluster_proportion_sample.pdf")
```

```{r}
base_clusterplt +
  geom_bar(aes(fill = predicted.id)) +
  scale_fill_discrete(name = "Cell Type") +
  scale_y_continuous(limits = c(0,2000), expand = c(0,0)) +
  facet_grid(1 ~ Cluster_Type, 
             space = 'free', 
             scales = 'free', labeller = label_wrap_gen(width = 10)) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        strip.text.y = element_blank(),
        strip.background.y = element_blank(),
        strip.background.x = element_blank())

ggsave("plots/cluster_proportion_celltype.pdf")

```

