---
title: "DEG Report"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

sobj <- tar_read(archived_sobj)
de_table <- tar_read(bulk_de_table)

protoplast_loci <- bulk_de_table %>%
  filter(p_adj_proto < 0.1 & abs(logFC_proto) > 0.5) %>%
  pull(Locus)

cluster_de_genes <- tar_read(cluster_sample_deg) %>%
  filter(!(Locus %in% protoplast_loci))

filtered_cluster_de_genes <- cluster_de_genes %>% 
  filter(p_val_adj < 0.01) %>%
  filter(abs(avg_log2FC) > 0.5)

bulk_de_table <- tar_read(bulk_de_table) %>%
  filter(!(Locus %in% protoplast_loci))
```

```{r}
cluster_markers <- tar_read(cluster_deg)
write_csv(cluster_markers, file = "data/cluster_markers.csv")
```

```{r}
immunity_genes <- filtered_cluster_de_genes %>%
  filter(str_detect(set1, "Immunity")) %>%
  pull(Locus) %>% 
  unique()

transition_genes <- filtered_cluster_de_genes %>%
  filter(str_detect(set1, "Transition")) %>%
  pull(Locus) %>% 
  unique()

susceptibility_genes <- filtered_cluster_de_genes %>%
  filter(str_detect(set1, "Susceptibility")) %>%
  pull(Locus) %>% 
  unique()

bulk_genes <- bulk_de_table %>% filter(p_adj_treat < 0.01 & abs(logFC_treat) > 1) %>% pull(Locus)

gene_list <- list(Susceptibility = susceptibility_genes,
                  Immunity = immunity_genes,
                  Transition = transition_genes)
                  #Pseudotime_Variable = pt_genes,
                  #Bulk = bulk_genes)

pdf(file="plots/de_upset.pdf")
UpSetR::fromList(gene_list) %>% UpSetR::upset()
dev.off()

UpSetR::fromList(gene_list) %>% UpSetR::upset()
```

```{r}
de_comparison <- cluster_de_genes %>% 
  left_join(bulk_de_table) %>% 
  mutate(Cluster_Type = str_match(set1, "_(.*)")[,2]) %>%
  mutate(is_de_in_bulk = Locus %in% bulk_genes) %>%
  mutate(Cluster_Type = factor(Cluster_Type, levels = c(
    "Immunity Mesophyll",
    "Transition Mesophyll",
    "Susceptibility Mesophyll",
    "Other Mesophyll",
    "Companion",
    "Bundle Sheath",
    "Vasculature",
    "Guard"
  )))

ggplot(de_comparison, aes(x = avg_log2FC, y = logFC_treat)) + 
  geom_bin2d(binwidth = c(0.15, 0.15)) + 
  scale_fill_viridis_c(option = "plasma") +
  facet_grid(is_de_in_bulk ~ Cluster_Type) +
  coord_equal(ratio = 0.5) +
  theme_bw()

ggsave("plots/bulk_vs_sc_de_comparison.pdf", family = "ArialMT", height = 8, width = 16)
```

