---
title: "GO tables"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)

sobj <- tar_read(archived_sobj)
```

## Select interesting GO terms from larger GO analysis

```{r}
marker_go <- targets::tar_read(marker_go) %>% 
  mutate(p.adj = p.adjust(classic, method = "BH"),
         seurat_clusters = as.character(cluster) %>% as.numeric()) %>%
  left_join(tar_read(archived_clusterNames)) %>%
  mutate(Enrichment = Significant / (Expected+1))

selected_go_terms <- marker_go %>% 
  mutate(p.adj = p.adjust(classic, method = "BH")) %>% 
  filter(p.adj < 0.01) %>% 
  group_by(cluster) %>% 
  slice_min(p.adj, n = 20) %>% 
  pull(GO.ID) %>% 
  unique()
```

## Display top 10 GO terms for each cluster

```{r}
map(unique(marker_go$cluster), function(clust) {
  go_data <- filter(marker_go, cluster == clust)
  go_data <- filter(go_data, classic < 0.001)
  go_data <- arrange(go_data, classic)
  go_data <- slice_min(go_data, classic, n = 10)
  kable(go_data, caption = paste0("Cluster ", clust), format = "html") %>% 
    kable_styling(full_width = FALSE)
})
```

## Save cluster GO terms

```{r}
write_csv(marker_go, file = "data/go_for_cluster_markers.csv")
write_csv(marker_go %>% group_by(cluster) %>% slice_min(classic, n = 10), 
          file = "data/go_for_cluster_markers_top5.csv")
```

## Heatmap of top GO terms by cluster

```{r}
go_mat <- marker_go %>% 
  filter(GO.ID %in% selected_go_terms) %>%
  select(GO.ID, cluster, Enrichment) %>%
  pivot_wider(names_from = "cluster", values_from = "Enrichment") %>%
  column_to_rownames("GO.ID")

go_hclust <- dist(go_mat) %>% hclust() 
go_order <- go_hclust$labels[go_hclust$order]


labels <- marker_go %>% 
  filter(GO.ID %in% selected_go_terms) %>%
  select(GO.ID, Term) %>%
  deframe()

ggplot(
  marker_go %>% 
    filter(GO.ID %in% go_order) %>%
    mutate(GO.ID = factor(GO.ID, levels = go_order)) %>%
    mutate(Cluster = factor(
      Cluster, 
      levels = c(
        paste0("M",1:14),
        paste0(c("B","P","G","C"),c(15:18))))),
  aes(x = Cluster, y = GO.ID)) +
  geom_tile(aes(fill = Enrichment)) +
  scale_fill_viridis_c() +
  scale_y_discrete(labels = labels)

ggsave("plots/go_heatmap.pdf", family = "ArialMT", width = 18, height = 12)
```

## JA and SA response

```{r}
## Get GO terms for JA
go_desc <- c(
  "response to jasmonic acid",
  "response to salicylic acid"
)

map(
  .x = go_desc, 
  .f = function(desc) {
    go_terms <- tar_read(gene_annotation) %>% 
      filter(GO_Description == desc) %>% 
      pull(GO) %>% 
      unique()
    
    genes <- tar_read(gene_annotation) %>% 
      filter(GO %in% go_terms) %>% 
      pull(Locus) %>% 
      unique()
    
    sobj <- AddModuleScore(sobj, list(genes), name = desc, assay = "SCT")
    
    cell_data <- get_cell_data(sobj) %>% 
      mutate(Cluster_Type = factor(Cluster_Type, levels = c(
        "Other Mesophyll",
        "Immunity Mesophyll",
        "Transition Mesophyll",
        "Susceptibility Mesophyll",
        "Bundle Sheath",
        "Companion",
        "Vasculature",
        "Guard"
      ))) %>% 
      mutate(Cluster = factor(Cluster, levels = c(
        paste0("M", 1:14),
        paste0(c("B","P","G","C"), 15:18)
      )))
    
    color_scheme <- tar_read(archived_clusterNames) %>% 
      dplyr::select(Cluster, Color) %>% 
      deframe()
    
    ggplot(cell_data %>% mutate(), aes(x = Cluster, y = !!as.name(paste0(make.names(desc), "1")))) + 
      geom_boxplot(aes(fill = Cluster)) +
      geom_jitter(alpha = 0.1) +
      scale_fill_manual(values = color_scheme) +
      ggtitle(desc) + 
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5))
    
    ggsave(paste0("plots/go_boxplot_", desc, ".pdf"))
  }
)

```