---
title: "Pseudotime Report"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data from archive

```{r}
sobj <- tar_read(atpst_sobj)
cds <- tar_read(atpst_mobj)
ptvar_genes <- tar_read(pt_var_genes)

mumap <- as.data.frame(reducedDims(cds)[["UMAP"]]) %>% 
    as_tibble(rownames = "Cell") %>% 
    select(Cell, mUMAP_1 = V1, mUMAP_2 = V2)

pt <- enframe(pseudotime(cds, reduction_method = 'UMAP'), "Cell", "Pseudotime")

cell_data <- get_cell_data(sobj) %>%
  left_join(mumap) %>%
  left_join(pt)
```

## Plot monocle trajectory

```{r}
color_scheme <- tar_read(archived_clusterNames) %>%
  select(Cluster, Color) %>%
  deframe()

plot_cells(cds, color_cells_by = "Cluster", trajectory_graph_segment_size = 0.75, label_cell_groups = F, label_branch_points = F, label_leaves = F) + scale_color_manual(values = color_scheme)

ggsave("plots/monocle_trajectory.pdf", family = "ArialMT")
```

## Plot expression of known genes vs. pseudotime

```{r}
apriori_genes <- read_csv("data/apriori_immune_and_susceptible.csv", col_types = cols())
plot_pt_heatmap(sobj, pt, apriori_genes, gene_names = tar_read(gene_ids)) + 
  facet_grid(Category ~ 1, scales = 'free') +
  theme(strip.background = element_blank())

ggsave("plots/pseuotime_heatmap_apriori.pdf", family = "ArialMT", height = 12, width = 8)
```

## Plot expression of novel genes vs. pseudotime

```{r}
pt_plt <- plot_pt_heatmap(
  sobj = sobj, 
  pt = pt, 
  goi = tibble(Locus = ptvar_genes), 
  gene_names = tar_read(gene_ids), 
  nclusters = 7) +
  facet_grid(Module ~ 1, scales = 'free') +
  theme(axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_blank()
  )

pt_plt

ggsave("plots/pseudotime_heatmap_novel.pdf", plot = pt_plt, height = 10, width = 8, family = "ArialMT")
```

## Write data for novel genes to a table.

```{r}
modules <- select(pt_plt$data, Locus, Module) %>% unique()

tar_read(pt_var_table) %>% left_join(modules) %>% write_csv("data/pseudotime_variable_genes.csv")
```

